services:
  web:
    image: webshop:latest
    container_name: webshop-ui
    ports:
      - 8000:3000
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - buymeshop-network

  server:
    image: server:latest
    container_name: mock-server
    ports:
      - 8001:3001
    restart: unless-stopped
    depends_on:
      - pg_db
    networks:
      - buymeshop-network
    environment:
      - DATABASE_URL=${POSTGRES_URL}

  pg_db:
    image: postgres:latest
    container_name: buymeshop-postgres-db
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./db_data:/var/lib/postgresql/data
    networks:
      - buymeshop-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - buymeshop-network
networks:
  buymeshop-network:
    driver: bridge