apiVersion: apps/v1
kind: Deployment
metadata:
  name: buymeshop-server
  labels:
    app: buymeshop-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: buymeshop-server
  template:
    metadata:
      labels:
        app: buymeshop-server
    spec:
      containers:
      - name: buymeshop-server
        image: buymeshop_backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: logs
          mountPath: /src/logs
        - name: certs
          mountPath: /src/certs
        envFrom:
        - configMapRef:
            name: buymeshop-env
      volumes:
      - name: logs
        hostPath:
          path: /home/ubuntu/longdb/shopwebsite/logs
      - name: certs
        hostPath:
          path: /home/ubuntu/longdb/shopwebsite/k8s/certs
---
apiVersion: v1
kind: Service
metadata:
  name: buymeshop-server
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30081
  selector:
    app: buymeshop-server
