apiVersion: v1
kind: ConfigMap
metadata:
  name: buymeshop-env
  namespace: default
  labels:
    app: buymeshop
    environment: production
data:
  POSTGRES_USER: buymeshop
  POSTGRES_PASSWORD: buymeshop
  POSTGRES_DB: buymeshop
  POSTGRES_HOST: pg-db
  POSTGRES_PORT: "5432"
  POSTGRES_URL: postgresql://buymeshop:buymeshop@pg_db:5432/buymeshop
  ES_PORT: "9201"
  KIBANA_PORT: "5602"
  ELASTIC_PASSWORD: 
  KIBANA_PASSWORD: password
  STACK_VERSION: "9.0.0"
  CLUSTER_NAME: buymeshop-cluster
  LICENSE: basic
  ELASTIC_API_KEY:
  ELASTIC_ENDPOINT: https://es01:9200
  ELASTIC_CERT_PATH: certs/ca/ca.crt
  ES_INDEX_NAME: buymeshop_products
  LLM_MODEL: llama-3.1-8b-instant
  LLM_API_KEY:
  LLM_TEMPERATURE: "0.1"
  SECRET_KEY: buymeshop
