replicas: 1

volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi

tls:
  enabled: true
  selfSignedCertificate:
    enabled: true

service:
  type: LoadBalancer
  ports:
    - name: https
      port: 30200
      protocol: TCP
      targetPort: 9200

esJavaOpts: "-Xmx1g -Xms1g"

resources:
  requests:
    cpu: "500m"
    memory: "2Gi"
  limits:
    cpu: "1"
    memory: "2Gi"

nodeSelector: {}
tolerations: []
affinity: {}
