apiVersion: apps/v1
kind: Deployment
metadata:
  name: webshop-ui
  labels:
    app: webshop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webshop-ui
  template:
    metadata:
      labels:
        app: webshop-ui
    spec:
      containers:
      - name: webshop-ui
        image: webshop:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: webshop-ui
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30083
  selector:
    app: webshop-ui
